### ISSUE TITLE
Make it possible to choose backends we want to try

### ISSUE THREAD

**Issue by rajatgoel** [hgst/libzbc#11]
I think there should be an easy way to choose the device types we want to try in `zbc_open`. If you guys are ok with adding another parameter to `zbc_open` (say a bitmask enabling/disabling) device types, I can work on a diff for that.

**Comment by hgst** [comment]
Hi Rajatgoel,

Of course this can be done, but I am not sure there is any benefit to that.
If you consider a host-managed disk:
1) An SAS disk will run only with the SCSI backend
2) A SATA disk will run only with the SATA backend on a standard kernel.
3) A SATA disk can run with the block backend or the SCSI backend if the kernel has SMR support (being implemented now), assuming the disk is connected to a SATA port or to a SAS HBA implementing ZBC/ZAC command translation (none support this now as far as I know)
4) A regular disk or a file will run only with the fake backend

zbc_open test the different backends in order until one says "OK", resulting in the behavior described above. That is, the only backend that can work. So forcing a specific backend can only result in an error unless the right one is forced.

The only exception to this is with a kernel implementing SMR support. In this case, the choice can be between the block backend, or the the scsi or sata backends. Forcing the block backend can be done by specifying the block device file path. The scsi or sata backend will be used if the SG node path is specified. Note that as the kernel SMR support matures, with SAS HBAs implementing ZBC/ZAC command translation, the sata backend could be removed entirely.

The same applies to host-aware disk which will be exposed also as a standard block device on a regular kernel.

Did you have any specific use for this proposal ?

Best regards.

Damien Le Moal,
HGST / Western Digital

**Comment by rajatgoel** [comment]
Hi, thanks for the detailed response. In some use-cases I am using libzbc to identify kind of a given disk. In those cases, I don't want libzbc to start using fake backend for a regular disk. Maybe a better solution is to have a separate top-level method to identify disk type?

**Comment by hgst** [comment]
Hi Rajatgoel,

I understand. Indeed, a function to test if a file path points to a SMR disk would be useful to have.
I will add a function for this. Look for a commit today or tomorrow.

Note that once the kernel gets SMR support, a file under /sys/block/<dev>/... will indicate this.

Thank you.

Best regards.
