### ISSUE TITLE
 Errors of runing zbc_test.sh in libzbc-master

### ISSUE THREAD

**Issue by zhaoyajun** [hgst/libzbc#13]
Hi,
       I am trying compile-and-install  libzbc-master following README,but when runing zbc_test.sh in libzbc-master there are errors :Test program zbc_test_close_zone not found in directory /home/zhaoyajun/Documents/libzbc-master/test/programs . 
    Whether or not /test/programs/close_zone/Makemodule.am do not run ,I need your help.
    Thanks .
    David

**Comment by hgst** [comment]
Hi David,

I checked from a fresh clone of the project, and after executing
"sh autogen.sh; configure --with-test; make"
the program zbc_test_close_zone is present in libzbc/test/programs.
Running the tests does not generate any error for me.

Please verify that you have the latest code (git status / git pull) and try to reconfigure/recompile. Everything should work. If the problem persists, please try to locate any error message in the configuration and compilation and report back.

Thank you.

Best Regards.

Damien Le Moal,
HGST / WD.

**Comment by zhaoyajun** [comment]
Hi Damien Le Moal, 
       I'm trying to build on Ubuntu 14.04LTS (yes, it's back-level)  and Fedora23 machine ,
and am running into a same problem , I don't know how to solve.the problem isn't solved,
Error Message are added to the attachment, I need your help.
Thanks.
David
[MyTest.txt](https://github.com/hgst/libzbc/files/162530/MyTest.txt)
[configure_log.txt](https://github.com/hgst/libzbc/files/162533/configure_log.txt)

**Comment by hgst** [comment]
Hi David,

To enable the compilation of the test programs, you need to run:

./configure --with-test

The normal "./configure" will *not* trigger the compilation of the test programs.

Best regards.

Damien Le Moal,
HGST / WD.

**Comment by zhaoyajun** [comment]
Hi Damien Le Moal,
    Ok,thanks.I solve it.
David
