### ISSUE TITLE
about logs of sg* or  ad*

### ISSUE THREAD

**Issue by zhaoyajun** [hgst/libzbc#14]
I ran the commands in the order posted. Most of tests hadn't succeed, such as zbc_set_zones.
I have attached a terminal log script. Please have a look
[test.txt](https://github.com/hgst/libzbc/files/183490/test.txt)

Thanks
Sincerely

David

**Comment by hgst** [comment]
Hi David,

libzbc emulation mode works only with regular block devices or regular files. As a result, zbc_set_zones will operate only with a regular block device (e.g. /dev/sdxxx) or a regular file. It will fail if you specify an SG node. This is why the tests execution with /dev/sg2 in your example behave strangely.

I pushed several fixes to remove misleading error messages and to stop the tests when an unsupported device is specified. This should fix all the problems you saw.

Best regards.

Damien Le Moal,
HGST / WD
