### ISSUE TITLE
cannot build v4.3.1

### ISSUE THREAD

**Issue by andybrown668** [hgst/libzbc#17]
I can build v4.3.0 but v4.3.1 fails with 

`lib/zbc_block.c:29:28: fatal error: linux/blkzoned.h: No such file or directory`

The build machine is on kernel 4.4.0-42-generic and I've got the kernel headers installed.

**Comment by hgst** [comment]
Andy,

The missing file is part of the 4.10 kernel block development tree and so not yet released.
I just pushed v4.3.2 which fixes this problem.

Best regards.
