### ISSUE TITLE
Fake ZBC Driver Metadata is not persisted across power cycle

### ISSUE THREAD

**Issue by TweakySolution** [hgst/libzbc#26]
I'm doing host restart testing where we power down the host after I/O is written and then verify the host data on power on. Nothing should be in-flight when the power down occurs.

Prior power loss I see sectors being written
`(libzbc) /data/fake/fakesmr3: Write 784 sectors at sector 218352`

However after a power cycle the zone is empty, resulting in I/O errors
`(libzbc) /data/fake/fakesmr3: Read 784 sectors at sector 218352
(libzbc) [ERROR] /data/fake/fakesmr3: Read 784 sectors at sector 218352 failed 5 (Input/output error)`

Using zbc_report_zones I can easily see there are zones we have written to but remain empty following power-cycle, including our zone with the target read
`
Zone 00100: type 0x2 (Sequential-write-required), cond 0xe (Full), reset recommended 0, non_seq 0, sector 204800, 2048 sectors, wp 206848
Zone 00101: type 0x2 (Sequential-write-required), cond 0xe (Full), reset recommended 0, non_seq 0, sector 206848, 2048 sectors, wp 208896
Zone 00102: type 0x2 (Sequential-write-required), cond 0xe (Full), reset recommended 0, non_seq 0, sector 208896, 2048 sectors, wp 210944
Zone 00103: type 0x2 (Sequential-write-required), cond 0xe (Full), reset recommended 0, non_seq 0, sector 210944, 2048 sectors, wp 212992
Zone 00104: type 0x2 (Sequential-write-required), cond 0xe (Full), reset recommended 0, non_seq 0, sector 212992, 2048 sectors, wp 215040
Zone 00105: type 0x2 (Sequential-write-required), cond 0x1 (Empty), reset recommended 0, non_seq 0, sector 215040, 2048 sectors, wp 215040
Zone 00106: type 0x2 (Sequential-write-required), cond 0x1 (Empty), reset recommended 0, non_seq 0, sector 217088, 2048 sectors, wp 217088
Zone 00107: type 0x2 (Sequential-write-required), cond 0x1 (Empty), reset recommended 0, non_seq 0, sector 219136, 2048 sectors, wp 219136
Zone 00108: type 0x2 (Sequential-write-required), cond 0x1 (Empty), reset recommended 0, non_seq 0, sector 221184, 2048 sectors, wp 221184
`
The question I have is does the fake driver support power-loss testing? It's almost like the metadata isn't synchronized with the process and data is loss. Does this seem like a sound understanding of the problem?

**Comment by damien-lemoal** [comment]
libzbc fake driver emulates the behavior of a real disk not only for data write to zone but also including the drive side write caching. With the fake driver, the write cache is the backend file page cache in kernel. The function zbc_flush() will force a sync of all data and metadata of the backend file in the case of the fake driver. That correspond to issuing a synchronize cache command to a real disk. Without this sync operation, any data (and zone WP change) that is not stored on the medium (not synced) will be lost on power loss.

It looks that this is exactly what you are experiencing. Is your application using zbc_flush() ? Using this function is the only solution to ensure no data loss (again exactly as with a real drive). If you already have defined in your application synchronization points executing zbc_flush() and you still see loss of data or incorrect WP values for data written BEFORE the zbc_flush() call, then this is a bug and I will need to dig into it. Please confirm.

Another note: for emulating a ZBC drive, libzbc fake driver is OK, but I would recommend using tcmu-runner ZBC emulation. tcmu-runner will expose a fake drive through the kernel scsi target driver to your application. The application will not be able to tell the difference with a real drive. In that case, libzbc scsi driver will be used, not the emulation driver. tcmu-runner can be found at: https://github.com/open-iscsi/tcmu-runner

**Comment by TweakySolution** [comment]
I should have mentioned I was using O_DIRECT and was expecting the metadata to sync alongside the data transfer. Regardless, I added a call to zbc_flush() after each zbc_write and now, following a host reset, I'm unable to issue a report zones to the zbc device.  I added some debug and it would appear we cannot acquire the lock. This occurs in both my code and the libzbc support code. I added some debug before and after the lock and never see lock acquired.

> [root@target-nate-2 bin]# zbc_report_zones -v -nz 1 /data/fake/fakesmr4
(libzbc) /data/fake/fakesmr4: ########## Trying SCSI driver ##########
(libzbc) /data/fake/fakesmr4: ########## SCSI driver failed -6 ##########
(libzbc) /data/fake/fakesmr4: ########## Trying ATA driver ##########
(libzbc) /data/fake/fakesmr4: ########## ATA driver failed -6 ##########
(libzbc) /data/fake/fakesmr4: ########## Trying FAKE driver ##########
(libzbc) /data/fake/fakesmr4: SG_GET_SG_TABLESIZE ioctl failed 25 (Inappropriate ioctl for device)
(libzbc) /data/fake/fakesmr4: Maximum command data transfer size is 1024 sectors
(libzbc) /data/fake/fakesmr4: using meta file /config/fake/zbc-fakesmr4.meta
(libzbc) /data/fake/fakesmr4: 786432 sectors of 4096B, 3072 zones
(libzbc) /data/fake/fakesmr4: ########## FAKE driver succeeded ##########
Device /data/fake/fakesmr4:
    Vendor ID: FAKE HGST HM libzbc
    Emulated zoned block device interface, Host-managed zone model
    6291456 512-bytes sectors
    786432 logical blocks of 4096 B
    786432 physical blocks of 4096 B
    3.221 GB capacity
    Read commands are restricted
    Maximum number of open sequential write required zones: 32
(libzbc) /data/fake/fakesmr4: locking fdev

I should see a "lock acquired" msg after the call to lock. Any ideas on how to proceed?

**Comment by damien-lemoal** [comment]
For a real device, O_DIRECT means "direct I/O to the device, bypassing kernel page cache" and does not imply "direct to the device medium". In other word, an O_DIRECT write() system call will not set the FUA (force unit access) bit in the write command sent to the disk. The write processing will depend on the write cache setting of the disk. So even with O_DIRECT, zbc_flush() will be needed.

For the locking problem you observed, this definitely looks like a bug. I will look into it.

**Comment by TweakySolution** [comment]
For the locking problem I added a call to `zbc_fake_unlock(fdev)` immediately after the mmap call in zbc_fake_open_metadata. The theory being we lost power while the metadata file was locked. I don't know if that's a viable solution but it seems to have worked so far.

**Comment by damien-lemoal** [comment]
Ah. Yes. That may be it: the lock initialization on metadata open never assumed that the lock may have been left in a locked by a crash/power event. In that case, the lock needs to be reinitialized, which the call to unlock() does, not safely though. Will fix this.

Thanks for the hint !
