### ISSUE TITLE
Max Segments assuming device path

### ISSUE THREAD

**Issue by TweakySolution** [hgst/libzbc#28]
In using a custom symbolic link for the device path, the `zbc_sg_max_segments` code will fail to read the max segments as it is assuming the absolute device path.

Add code to check if the zbd_filename is a link and decode the link. Something like:
```
/**
 * Gets the absolute device path from the input device
 */
static void zbc_sg_device_path(struct zbc_device *dev, char *path, int path_len)
{
	struct stat lst;
	ssize_t len;


    strncpy(path, dev->zbd_filename, path_len);

    if (lstat(dev->zbd_filename, &lst) == 0) {
        if (S_ISLNK(lst.st_mode)) {
            len = readlink(dev->zbd_filename, path, path_len-1);
            if (len < 0) {
                zbc_error("%s: readlink failed %d (%s)\n",
                           dev->zbd_filename,
                           errno, strerror(errno));
            } else {
                path[len] = '\0';
            }
        }
    }
}
```

**Comment by damien-lemoal** [comment]
Nathaniel,

Yes, indeed, the symbolic link case is not being handled correctly. I will look into this. Thank you for signaling the problem.

**Comment by TweakySolution** [comment]
Thanks Damien!

As a secondary item, we're looking to increase the `max_segments` value to something like 2048 (if possible; I'm still investigating). This will exceed the system queue configuration `max_sectors_kb`; which currently defaults to 1280 KB but can be configured up to 2560 KB. Should the code be taking the minimum of both values when computing the max transfer length?

Low urgency on each item; appreciate your help.

**Comment by damien-lemoal** [comment]
Nathaniel,

I just pushed a fix in the staging branch. Could you please check if that code solves all your problems ?

**Comment by TweakySolution** [comment]
@damien-lemoal Changes look good - I'm seeing the correct maximum returned from the sg driver.

Thank you!
