### ISSUE TITLE
Support for vector I/O preadv & pwritev

### ISSUE THREAD

**Issue by TweakySolution** [hgst/libzbc#30]
I was going to add support for vector I/O with new zbc_preadv and zbc_pwritev interfaces with your approval.

One question I have before getting started is if vector I/O is supported by Direct I/O when using the sg driver.

In here: https://www.tldp.org/HOWTO/pdf/SCSI-Generic-HOWTO.pdf
I see
> Furthermore iovec_count's variety of scatter gather (into the user space) is only available when normal (or "indirect") IO is being used. Hence when the SG_FLAG_DIRECT_IO or SG_FLAG_MMAP_IO are set in 'flags' then 'iovec_count' should be zero.

However, inspecting the 4.20 kernel, I don't see any limitation so perhaps this statement is obsolete. Are you aware?

As an experiment I added a single `sg_iovec_t iovec[1];` to `zbc_sg_cmd` and funneled all I/O through this single vector in `zbc_sg_cmd_init`. I think this is a decent hack
```	
	if (cmd->out_bufsz) {
		cmd->io_hdr.dxferp = cmd->iovec;
		cmd->io_hdr.iovec_count = 1;
		cmd->iovec[0].iov_base = cmd->out_buf;
		cmd->iovec[0].iov_len = cmd->out_bufsz;
	}
```

I'm not seeing any errors with reads or writes. Do you think this is enough to prove this out?

**Comment by damien-lemoal** [comment]
I am OK with adding this interface. I think it should all work as long as all vectors buffer and size have the proper alignment. Let me check the kernel code too. Could you also try your test with more than one vector ?

**Comment by damien-lemoal** [comment]
In the kernel, the SG driver (driver/scsi/sg.c) has this code in sg_start_req():

        if (sg_allow_dio && hp->flags & SG_FLAG_DIRECT_IO &&
            dxfer_dir != SG_DXFER_UNKNOWN && !iov_count &&
            !sfp->parentdp->device->host->unchecked_isa_dma &&
            blk_rq_aligned(q, (unsigned long)hp->dxferp, dxfer_len))
                md = NULL;
        else
                md = &map_data;

        if (md) {
                ...
                        res = sg_build_indirect(req_schp, sfp, dxfer_len);

Which means that for a direct I/O request with iov_count > 0, indirect I/Os are being used. This is why you do not see any problem. Direct I/Os is ineffective. So SG how-to statement is still valid. No errors will happen, but direct I/Os will not be used either.

**Comment by TweakySolution** [comment]
Great, thanks Damien. I'm going to abandon the effort.

**Comment by TweakySolution** [comment]
I've been asked again to look at this so I have re-opened the ticket. Same plan as before
> Add support for vector I/O with new zbc_preadv and zbc_pwritev interfaces.

For the test tools I was think of adding a -iov option to read_zone / write_zone instead of cloning all the functionality. Does this seem appropriate?

**Comment by TweakySolution** [comment]
Gave it a go today and came up with the following PR #32

**Comment by damien-lemoal** [comment]
I am OK with the idea of zbc_preav() and zbc_prwritev(). However, as explored last time, if the SG driver is being used, then direct I/Os become buffered I/Os. Are you OK with that ?
As for the iov_len, yes, for consistency, we need to keep the the 512B sector unit. The alignment checks done in pread()/pwrite() need to be applied to each iov passed.

Please give me some time to review your PR.

**Comment by TweakySolution** [comment]
> However, as explored last time, if the SG driver is being used, then direct I/Os become buffered I/Os. Are you OK with that?

Yes, either the copy-to-page-aligned-memory occurs on the userspace side or we offload it to the kernel.

I did leave a small optimization in the PR where if you specify direct I/O and `iovcnt == 1` then we drop the iov and resort to the current behavior. Thinking about it overnight, I'm uncertain on this; It might be better for the preadv/pwritev to always use the iov code. - I can make the same decision in my client side code before calling preadv.

**Comment by damien-lemoal** [comment]
Now supported in new 5.8.0 release.

**Comment by TweakySolution** [comment]
Thanks @damien-lemoal
