### ISSUE TITLE
configure: error: Couldn't find scsi/sg.h

### ISSUE THREAD

**Issue by apkulkarni86** [hgst/libzbc#40]
I'm trying to build libzbc v5.8.5 on an Oracle Linux VM - 4.14.35-1902.3.2.el7uek.x86_64. The configure step fails with this error:

./configure --with-test CFLAGS=-fPIC
.
.
.
checking whether more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
checking for scsi/scsi.h... yes
checking for scsi/sg.h... no
configure: error: Couldn't find scsi/sg.h

I've had no luck building this on physical machine with the same OS installed as well. I get the same error. Any ideas, what's going on?

**Comment by apkulkarni86** [comment]
Another data point: 
I was able to build v5.8.4 successfully. Something changed between v5.8.4 and v5.8.5 that's breaking the build.

**Comment by apkulkarni86** [comment]
This commit seems to introduce the problem:

```
commit a7c03a90a695a36ec3f7d04bdfee26630f5c1b66
Author: Damien Le Moal <damien.lemoal@wdc.com>
Date:   Tue Apr 7 15:33:21 2020 +0900

    configure: Fix AC_CHECK_HEADERS use
    
    Avoid the annoying "present but cannot be compiled" error return
    from AC_CHECK_HEADERS by defining the macro fourth argument as
    recommended by gnu.org documentation.
    
    Signed-off-by: Damien Le Moal <damien.lemoal@wdc.com>

```

**Comment by damien-lemoal** [comment]
As mentioned in the README file, the autoconf-archive package is a requirement. Can you please check if this package is installed on your system ? If it is not, please install it and retry.

Note: the CFLAGS=-fPIC option is not needed. That compilation option is always set by configure.

**Comment by apkulkarni86** [comment]
I had autoconf-archive-2017.03.21-1.el7.noarch installed on my system per instructions in the README. Haven't been able to build it. 
Good to know about the fPIC flag. Thanks!

**Comment by damien-lemoal** [comment]
Weird... Checked again on my (fedora) system and all is good. Doing some manual testing, the absence of the "main()" function is the code to be compiled to check for the header does return an error depending on how that compilation is done. Which makes me think that we are seeing differences in how AC_CHECK_HEADERS are implemented.

Could you try the following patch:

```
diff --git a/configure.ac b/configure.ac
index f2fc6242..e840d1fd 100644
--- a/configure.ac
+++ b/configure.ac
@@ -46,26 +46,31 @@ AC_CHECK_HEADER([scsi/scsi.h], [],
                [AC_MSG_ERROR([Couldn't find scsi/scsi.h])],
                [
                        #include <scsi/scsi.h>
+                       int main(int argc, char **argv) { return 0; }
                ])
 AC_CHECK_HEADER([scsi/sg.h], [],
                [AC_MSG_ERROR([Couldn't find scsi/sg.h])],
                [
                        #include <scsi/scsi.h>
                        #include <scsi/sg.h>
+                       int main(int argc, char **argv) { return 0; }
                ])
 AC_CHECK_HEADER([libgen.h], [],
                [AC_MSG_ERROR([Couldn't find libgen.h])],
                [
                        #include <libgen.h>
+                       int main(int argc, char **argv) { return 0; }
                ])
 AC_CHECK_HEADERS([linux/fs.h], [],
                [AC_MSG_ERROR([Couldn't find libgen.h])],
                [
                        #include <linux/fs.h>
+                       int main(int argc, char **argv) { return 0; }
                ])
 AC_CHECK_HEADERS([linux/blkzoned.h], [], [],
                [
                        #include <linux/blkzoned.h>
+                       int main(int argc, char **argv) { return 0; }
                ])
 
 # Conditionals
```

And let me know if it works for you ?

**Comment by apkulkarni86** [comment]
Made the changes you suggested above. Still hitting the same issue.

**Comment by damien-lemoal** [comment]
OK. I think I am going to revert that patch then. It is really strange though. As far as I understand the autoconf documentation, this is done correctly...

**Comment by damien-lemoal** [comment]
Last try before reverting: could you please test the following change ?

```
From 67cdb3a32194fcc12ffff5445b183919316c771f Mon Sep 17 00:00:00 2001
From: Damien Le Moal <damien.lemoal@wdc.com>
Date: Fri, 15 May 2020 16:28:33 +0900
Subject: [PATCH] configure: Fix use of AC_CHECK_HEADER

Replace with AC_CHECK_HEADERS and fix the fourth argument value.

Signed-off-by: Damien Le Moal <damien.lemoal@wdc.com>
---
 configure.ac | 44 +++++++++++++++++++++++++++++---------------
 1 file changed, 29 insertions(+), 15 deletions(-)

diff --git a/configure.ac b/configure.ac
index f2fc6242..cd8c05f0 100644
--- a/configure.ac
+++ b/configure.ac
@@ -42,31 +42,45 @@ LIBS="$PTHREAD_LIBS $LIBS"
 CC="$PTHREAD_CC"
 
 # Checks for header files.
-AC_CHECK_HEADER([scsi/scsi.h], [],
+AC_CHECK_HEADERS([scsi/scsi.h], [],
                [AC_MSG_ERROR([Couldn't find scsi/scsi.h])],
-               [
+               [[
+                       #ifdef HAVE_SCSI_SCSI_H
                        #include <scsi/scsi.h>
-               ])
-AC_CHECK_HEADER([scsi/sg.h], [],
+                       int main(int argc, char **argv) { return 0; }
+                       #endif
+               ]])
+AC_CHECK_HEADERS([scsi/sg.h], [],
                [AC_MSG_ERROR([Couldn't find scsi/sg.h])],
-               [
-                       #include <scsi/scsi.h>
+               [[
+                       #ifdef HAVE_SCSI_SG_H
                        #include <scsi/sg.h>
-               ])
-AC_CHECK_HEADER([libgen.h], [],
+                       int main(int argc, char **argv) { return 0; }
+                       #endif
+               ]])
+AC_CHECK_HEADERS([libgen.h], [],
                [AC_MSG_ERROR([Couldn't find libgen.h])],
-               [
+               [[
+                       #ifdef HAVE_LIBGEN_H
                        #include <libgen.h>
-               ])
+                       int main(int argc, char **argv) { return 0; }
+                       #endif
+               ]])
 AC_CHECK_HEADERS([linux/fs.h], [],
-               [AC_MSG_ERROR([Couldn't find libgen.h])],
-               [
+               [AC_MSG_ERROR([Couldn't find linux/fs.h])],
+               [[
+                       #ifdef HAVE_LINUX_FS_H
                        #include <linux/fs.h>
-               ])
+                       int main(int argc, char **argv) { return 0; }
+                       #endif
+               ]])
 AC_CHECK_HEADERS([linux/blkzoned.h], [], [],
-               [
+               [[
+                       #ifdef HAVE_LINUX_BLKZONED_H
                        #include <linux/blkzoned.h>
-               ])
+                       int main(int argc, char **argv) { return 0; }
+                       #endif
+               ]])
```

**Comment by apkulkarni86** [comment]
I'm still seeing the issue.

**Comment by damien-lemoal** [comment]
Arrg... OK. I am still trying to work around your issue to avoid reverting. I have received far too many emails about "Header Present But Cannot Be Compiled" problems... Could you please provide the following information:
- gcc, autoconf, autoconf-archive, automake and libtool package versions on your system
- Do you have the file /usr/include/scsi/sg.h present ? If no, where is it on your system ?

I would like to try to recreate your issue to see how it can be fixed.

**Comment by apkulkarni86** [comment]
`gcc version 4.8.5 20150623 (Red Hat 4.8.5-39.0.1) (GCC)`
`autoconf (GNU Autoconf) 2.69`
`Package autoconf-archive-2017.03.21-1.el7.noarch already installed and latest version`
`automake (GNU automake) 1.13.4`
`libtool (GNU libtool) 2.4.2`

Yes. I have sg.h at /usr/include/scsi/sg.h
`# ls /usr/include/scsi/sg.h 
/usr/include/scsi/sg.h`

**Comment by damien-lemoal** [comment]
I pushed some changes. The top patch should fix your problem. Please check !

**Comment by apkulkarni86** [comment]
That worked! Thanks for fixing this.
